const dataMapperConstants = {
  INIT_DATA_MAPPER_FIELDS: 'INIT_DATA_MAPPER_FIELDS',
  AUTO_SELECT_DATA_MAPPER_FIELDS: 'AUTO_SELECT_DATA_MAPPER_FIELDS',
  MAP_TARGET_FIELD_TO_DATA_FIELD: 'MAP_TARGET_FIELD_TO_DATA_FIELD',
  UN_MAP_TARGET_FIELD_TO_DATA_FIELD: 'UN_MAP_TARGET_FIELD_TO_DATA_FIELD',
  CHANGE_DATA_FIELD_MAPPER: 'CHANGE_DATA_FIELD_MAPPER',
  SET_FILE: 'SET_FILE',
  SET_MODEL: 'SET_MODEL',
  IMPORT_TO_ACCOUNT: 'DATA_MAPPER_IMPORT_ACCOUNT',
  RESET_IMPORTER: 'DATA_MAPPER_RESET_IMPORTER',
  SET_EXTRA_FIELD: 'SET_EXTRA_FIELD',
};

export default dataMapperConstants;
